title: Jojo
description: >-
  AI-powered job search tool that transforms applications into
  personalized marketing campaigns.
baseurl: ""
url: ""

theme: just-the-docs
plugins:
  - jekyll-feed

mermaid:
  version: "11.12.2"

aux_links:
  "Jojo on GitHub":
    - "//github.com/grymoire7/jojo"

aux_links_new_tab: true

exclude:
  - plans/
  - examples/
